tls:
  certificates:
    - certFile: "/certs/cert.pem"
      keyFile: "/certs/key.pem"

# Added security headers (HSTS, XSS protection)
http:
  middlewares:
    secure-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        frameDeny: true

    # Middleware for redirecting HTTP to HTTPS
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
